### ISSUE TITLE
print kml: not all files printed

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#2698]
open those 9 kmls
https://s.geo.admin.ch/6726e7076b

![unbenannt](https://cloud.githubusercontent.com/assets/4577727/10055204/38cddc4e-6235-11e5-956d-411bf893339e.png)

then print it to pdf

we miss one file
![unbenannt1](https://cloud.githubusercontent.com/assets/4577727/10055210/443a2d1c-6235-11e5-9b61-aaa9b262440b.PNG)

**Comment by oterral** [comment]
Works for me can you retest please? Which browser do you use?

**Comment by davidoesch** [comment]
Latent ff on win10 still have an isdue

**Comment by procrastinatio** [comment]
Works on Chrome and IE.

Can you send us the `spec`(the json file)  that is sent to `create.json`, so we can see if it is a client or a server issue ?

**Comment by cedricmoullet** [comment]
@procrastinatio could you double check ?

**Comment by procrastinatio** [comment]
[KML](https://public.geo.admin.ch/rK1YiwICTTeCY8jTmpdkBg) with random points (to test)

**Comment by procrastinatio** [comment]
To recap, this issue has nbothing to do with KML or vector features. The trouble is only that the print extent as displayed in map.geo.admin.ch does not match the PDF.

**Comment by davidoesch** [comment]
solution?

**Comment by procrastinatio** [comment]
The PR #2851 fixes this issue, my comment was just a recap to self of was the problem really was. Some point werenot printed, not because of buggy vector layer handling but missmatching print extent.

**Comment by oterral** [comment]
Fixed in prod

**Comment by davidoesch** [comment]
I reopen this and set it to prio 1, since this is still an issue reported frequently

eg here 
[map.geo.ch Test 4 Druckvorlage.pdf](https://github.com/geoadmin/mf-geoadmin3/files/66692/map.geo.ch.Test.4.Druckvorlage.pdf)

results in
![map geo ch test 4 ausdruck](https://cloud.githubusercontent.com/assets/4577727/11898935/d008b42c-a59b-11e5-8fa2-d780c8385df5.jpg)

not all elements are shown

**Comment by cedricmoullet** [comment]
@procrastinatio can you have a look at this one ?

**Comment by procrastinatio** [comment]
Could you provide some examples of buggy KML ? Do some KMLsystematically fail to print some features or is it completely random ? Is is imported KML or drawn features ? Or is it simply the resulting PDf which is buggy ?

**Comment by davidoesch** [comment]
Drawn features: https://public.geo.admin.ch/_ylHx2n3SECWZVZDqnp8iQ
imported  features :eg by gpsvisualizer like https://gist.githubusercontent.com/davidoesch/f6ed7ed436927da3cc35/raw/3e642dec62fcedf1305e6985060b9debe8137093/Viatimage%2520Alps 

 as decribed above: the resulting PDF which is buggy, links are ok

**Comment by procrastinatio** [comment]
Maybe related to https://github.com/geoadmin/mf-geoadmin3/issues/3016

**Comment by gjn** [comment]
@davidoesch Did you use Adobe Reader Pro to read the PDF's?

**Comment by davidoesch** [comment]
No the standard version of our bureau pc and the in chrome version. Both were giving b the same result

**Comment by davidoesch** [comment]
https://map.geo.admin.ch/?topic=ech&lang=de&bgLayer=ch.swisstopo.swissimage&layers=ch.swisstopo.zeitreihen,ch.bfs.gebaeude_wohnungs_register,ch.bafu.wrz-wildruhezonen_portal,ch.swisstopo.swisstlm3d-wanderwege,KML%7C%7Chttps:%2F%2Fpublic.geo.admin.ch%2F_ylHx2n3SECWZVZDqnp8iQ&layers_visibility=false,false,false,false,true&layers_timestamp=18641231,,,,&X=186051.89&Y=692273.89&zoom=11

**Comment by davidoesch** [comment]
@gjn here: @oterral can you have a look?

**Comment by oterral** [comment]
All features ar printed :)

**Comment by davidoesch** [comment]
Not by the user using this URL : I'll ask thenm again to reproduce . did you fix /change sth?

**Comment by oterral** [comment]
No all worked fine since we had closed the issue the first time.

**Comment by oterral** [comment]
@davidoesch news about this?

**Comment by davidoesch** [comment]
Still an issue : As described in the mail

**Comment by oterral** [comment]
Which mail @davidoesch ?

**Comment by gjn** [comment]
@davidoesch @oterral status?

**Comment by davidoesch** [comment]
Still issue
Am 03.03.2016 11:17 vorm. schrieb "Gilbert Jeiziner" <
notifications@github.com>:

**Comment by oterral** [comment]
still can't reproduce on my side

**Comment by davidoesch** [comment]
Gosh in This case I think I need to have a screen sharing session with the user... Since they can reproduce it all the time

**Comment by davidoesch** [comment]
I Clsoe this one for now becuase the client can only rproduce it on ONE device
