### ISSUE TITLE
Short URL with external data: generated / openedon iphone does not work

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#3828]
Reproduce 

Open desktop mode on iPhone 

Add via import

http://www.gis.stadt-zuerich.ch/wmts/wmts-zh-stzh-ogd.xml

Load a layer 

Generate a short URL 

Share it 

Result: short URL does not contain external source 

Same for this short URL has been generated on desktop https://s.geo.admin.ch/735fc46288
But on iPhone it won't load the kml
KML-File http://www.t.hgs.at/Logs/Data_OUT/KML/P91/20170519.kml

**Comment by oterral** [comment]
It is in the link but it is removed because  it can't add the layer.

**Comment by oterral** [comment]
The KML bug is caused by https://github.com/geoadmin/mf-geoadmin3/issues/3819 and fixed by https://github.com/geoadmin/mf-geoadmin3/pull/3829

**Comment by oterral** [comment]
Ah my bad the WMTS whcih doesn't stay in the URL is a bug. I fix and redeploy

**Comment by oterral** [comment]
Ok the permalink bug is fixed in 15min on production.

**Comment by davidoesch** [comment]
It is not fixed : Open the link to map.geo on https://www.wandern.ch/de/wandern/vorbereitung/campieren-und-biwakieren on iPhone

**Comment by davidoesch** [comment]
URL on site is wrong... Sorry
