### ISSUE TITLE
[MVT] F-001 : provide LBM style variation

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4584]
Since we dont have multiple datasets to show for MVT test viewer and we can't generate easily our variations on our own, we need an additional style so user can switch between styles to see the vector manipulation modus

Goal: besides the official LBM we would like to have an additional USER generated style in pulldown, which we link as third party style for https://github.com/geoadmin/mf-geoadmin3/issues/4581 

a nice style was mantioned here
https://github.com/geoadmin/config-tileservergl/pull/12

-> Can you @danduk82  organize this style for loic? 

if not  possible we just change the pallette of the current style using the same layers

**Comment by loicgasser** [comment]
A dark theme could also be nice. For fire fighters and the police.

**Comment by davidoesch** [comment]
I asked Sebastian die it

**Comment by davidoesch** [comment]
LSD Style as alternative for switch style (https://raw.githubusercontent.com/openmaptiles/fiord-color-gl-style/master/style.json)

pls up downvote @loicgasser @gjn @oterral 

[styles-ch.swisstopo.basiskarte-lsd.vt_v004.zip](https://github.com/geoadmin/mf-geoadmin3/files/2648930/styles-ch.swisstopo.basiskarte-lsd.vt_v004.zip)

**Comment by davidoesch** [comment]
*GREY* Style as alternative for switch style (https://raw.githubusercontent.com/openmaptiles/fiord-color-gl-style/master/style.json)

pls up downvote @loicgasser @gjn @oterral 

[styles-ch.swisstopo.leichte-basiskarte-grey.vt_v004.zip](https://github.com/geoadmin/mf-geoadmin3/files/2648941/styles-ch.swisstopo.leichte-basiskarte-grey.vt_v004.zip)

**Comment by davidoesch** [comment]
***basis*** Style as alternative for switch style (https://raw.githubusercontent.com/openmaptiles/fiord-color-gl-style/master/style.json)

pls up downvote @loicgasser @gjn @oterral 


[styles-ch.swisstopo.basiskarte.vt_v004.zip](https://github.com/geoadmin/mf-geoadmin3/files/2648943/styles-ch.swisstopo.basiskarte.vt_v004.zip)

**Comment by gjn** [comment]
I like them as well. And remember, the goal is not only to sell maps/styles, but it's to sell the possibilitie to create your own map. And showing people possibilities makes them hungry.

**Comment by swissgis3084** [comment]
The layer structure of all of these styles (lightbase, base, grey, lsd) is the same and it will remain like this (at least until we go public with the Testviewer). We will still be tuning the styles (set different colors, line widths, or whatever) but we will not change the layer structure. So it is stable and the Testviewer can be adapted to these styles.

**Comment by oterral** [comment]
Definitiv basis is the best :) you can compare the rendering with  Color map bg. The others are also good example.

**Comment by swissgis3084** [comment]
lightbase is our prime style we want to show (product management). it is light in color and (in the future) gives the user a possibility to add his own data with intense color, without making the map too heavy.

**Comment by loicgasser** [comment]
Great job. Basis for sure. And + 1 to add them all.

**Comment by davidoesch** [comment]
ok votes are done
proposal for loic just split the "switch layer" button to 3 buttons / radio buttons. lets name the style "A" "B" "C" not base lsd or grey

**Comment by oterral** [comment]
@davidoesch  translations added in excelsheeet:


vector_feedback_style_default
vector_feedback_style_color
vector_feedback_style_grey
vector_feedback_style_lsd

**Comment by swissgis3084** [comment]
@davidoesch can you publish **lightbase**? **lightbase** (not **base**) is the style i have been working on and it is the one we want to show. the others are just quick derivations of it. from PM point of view **base** is actually the least important style and we might not want to publish it at all (it looks like our normal "Landeskarte" but just a lot worse). use **lightbase** as default. then i suggest we add **grey** and may be **LSD**? I'm open to other suggestions

**Comment by swissgis3084** [comment]
the style of **lightbase** with all tiles aggregated in one tileset: http://tileserver.int.bgdi.ch/styles/ch.swisstopo.leichte-basiskarte_aggregated_osm.vt_v004/?vector#12.89/47.56015/7.60972

**Comment by davidoesch** [comment]
we  put buttons on one line

**Comment by davidoesch** [comment]
translations done: set button on one line, thanks @loicgasser

**Comment by loicgasser** [comment]
Ok will do

**Comment by davidoesch** [comment]
Hi @loic the gls-sytles still point to my private repo: can you use this urls instead
- https://cms.geo.admin.ch/www.geo.admin.ch/cms_api/gl-styles/styles-ch.swisstopo.basiskarte-lsd.vt_v004.json

-https://cms.geo.admin.ch/www.geo.admin.ch/cms_api/gl-styles/styles-ch.swisstopo.basiskarte.vt_v004.json

- https://cms.geo.admin.ch/www.geo.admin.ch/cms_api/gl-styles/styles-ch.swisstopo.leichte-basiskarte.vt_v004.json

thanks

**Comment by gjn** [comment]
We have other styles on public.geo.

Too many hosts, we have things everywhere.

Also, caching headers ok?

**Comment by davidoesch** [comment]
You can put them on public.Geo ... No issue. It's importer that those styles are not pay of the official product...

**Comment by davidoesch** [comment]
wait until we have v006

**Comment by swissgis3084** [comment]
in v006 all data will come from one mbtile:vektorkarte.vt (except the seperate osm data) and we will provide 3 styles: lightbase, grey and lsd (or just some really colorfull crazy stuff... not sure about it yet)

**Comment by davidoesch** [comment]
hi @swissgis3084 
we have 
https://vectortiles.geo.admin.ch/gl-styles/ch.swisstopo.leichte-basiskarte-grey.vt/v006/?vector#7/47/8.25
https://vectortiles.geo.admin.ch/gl-styles/ch.swisstopo.leichte-basiskarte-vintage.vt/v006/?vector#7/47/8.25

but the colourful one we still use the same we have for v004?

**Comment by davidoesch** [comment]
And here we go with the third variation

therefore we have now

A https://vectortiles.geo.admin.ch/gl-styles/ch.swisstopo.leichte-basiskarte-grey.vt/v006/?vector#7/47/8.25
B https://vectortiles.geo.admin.ch/gl-styles/ch.swisstopo.leichte-basiskarte-vintage.vt/v006/?vector#7/47/8.25
C http://tileserver.int.bgdi.ch/gl-styles/ch.swisstopo.leichte-basiskarte-lsd.vt/v006/?vector#7/47/8.5 

Store the style under cms.geo.admin.ch

**Comment by davidoesch** [comment]
Hi @boecklic 

the stalye varation as above  can NOT be seved via the official vectortiles.geo.admin.ch  URL they need to have the warning

as mentioned above in the ticket-- you guys should not move it from my private repo to the official service but to CMS or a github repo

as a courtesy: I moved it already for you to cms.geo.admin.ch

A) https://cms.geo.admin.ch/www.geo.admin.ch/cms_api/gl-styles/ch.swisstopo.leichte-basiskarte-grey.vt_v006.json 
B) https://cms.geo.admin.ch/www.geo.admin.ch/cms_api/gl-styles/ch.swisstopo.leichte-basiskarte-vintage.vt_v006.json 
C) https://cms.geo.admin.ch/www.geo.admin.ch/cms_api/gl-styles/ch.swisstopo.leichte-basiskarte-lsd.vt_v006.json 

without this fiy we can't go live

**Comment by davidoesch** [comment]
https://github.com/geoadmin/mf-geoadmin3/issues/4584#issuecomment-461021114 is not fixed 
is not attributed in [MVT] fixing background colour edition (GLStyle) #4820
![image](https://user-images.githubusercontent.com/4577727/56787789-e782b300-67fd-11e9-809c-9aaab40b5562.png)

**Comment by danduk82** [comment]
@pakb please check this too while solving the issue with the style edition...

**Comment by pakb** [comment]
I don't understand what I'm supposed to do, styles are stored in cms.geo.admin.ch, changing background works too.
Please clarify

**Comment by danduk82** [comment]
@davidoesch I think this is solved, can you confirm?

**Comment by davidoesch** [comment]
nope it is NOT solved 
style A B C are considered third party datasets

according to the spec
![image](https://user-images.githubusercontent.com/4577727/57007699-ef21cd80-6bea-11e9-9618-3aefd79c39d1.png)

this should also apply for style A B and C (but not for defautl since this is an official one), be sure that you also add the footer info where A B C is stored (https://github.com/geoadmin/mf-geoadmin3/issues/4662)

**Comment by boecklic** [comment]
Current behaviour of test.map.geo.admin.ch: red man icon only shown if any of [default,A,B,C] is modified, but not when just using [A,B,C]. Is this correct? Or should the icon be show for edited [default,A,B,C] and non-edited [A,B,C]?
Showstopper? Or can we do this in the next days?

**Comment by davidoesch** [comment]
-> RED activated icon be show for edited [default,A,B,C] and non-edited [A,B,C]

**Comment by boecklic** [comment]
and for
> Showstopper? Or can we do this in the next days?

**Comment by pakb** [comment]
When custom style, this UI elements are missing :
- [ ] red warning man
- [ ] footer info

Custom styles are :
- loading A B C layer
- changing  A B C style layer and saving it
- having an external style layer

**Comment by boecklic** [comment]
@boecklic commented: A dark theme could also be nice. For fire fighters and the police.

**Comment by boecklic** [comment]
@boecklic commented: I asked Sebastian for it

**Comment by boecklic** [comment]
@boecklic commented: ***LSD*** Style as alternative for switch style (https://raw.githubusercontent.com/openmaptiles/fiord-color-gl-style/master/style.json)

https://mf-chsdi3.int.bgdi.ch/mvt/shorten/7eaa1556fb 

pls up downvote @loicgasser @gjn @oterral 

[styles-ch.swisstopo.basiskarte-lsd.vt_v004.zip](https://github.com/geoadmin/mf-geoadmin3/files/2648930/styles-ch.swisstopo.basiskarte-lsd.vt_v004.zip)

**Comment by boecklic** [comment]
@boecklic commented: ***GREY*** Style as alternative for switch style (https://raw.githubusercontent.com/openmaptiles/fiord-color-gl-style/master/style.json)

https://mf-chsdi3.int.bgdi.ch/mvt/shorten/7eaa141479 

pls up downvote @loicgasser @gjn @oterral 

[styles-ch.swisstopo.leichte-basiskarte-grey.vt_v004.zip](https://github.com/geoadmin/mf-geoadmin3/files/2648941/styles-ch.swisstopo.leichte-basiskarte-grey.vt_v004.zip)

**Comment by boecklic** [comment]
@boecklic commented: ***basis*** Style as alternative for switch style (https://raw.githubusercontent.com/openmaptiles/fiord-color-gl-style/master/style.json)

https://mf-chsdi3.int.bgdi.ch/mvt/shorten/7eaa1277e3 

pls up downvote @loicgasser @gjn @oterral 


[styles-ch.swisstopo.basiskarte.vt_v004.zip](https://github.com/geoadmin/mf-geoadmin3/files/2648943/styles-ch.swisstopo.basiskarte.vt_v004.zip)

**Comment by boecklic** [comment]
@boecklic commented: to be honest   I like them all! why not just toggel through? or have 3 toggles in the feedback panel: GREY, COLOR, BASE

**Comment by boecklic** [comment]
@boecklic commented: I like them as well. And remember, the goal is not only to sell maps/styles, but it's to sell the possibilitie to create your own map. And showing people possibilities makes them hungry.

**Comment by boecklic** [comment]
@boecklic commented: The layer structure of all of these styles (lightbase, base, grey, lsd) is the same and it will remain like this (at least until we go public with the Testviewer). We will still be tuning the styles (set different colors, line widths, or whatever) but we will not change the layer structure. So it is stable and the Testviewer can be adapted to these styles.

**Comment by boecklic** [comment]
@boecklic commented: Definitiv basis is the best :) you can compare the rendering with  Color map bg. The others are also good example.

**Comment by boecklic** [comment]
@boecklic commented: lightbase (not yet on Testviewer) is our prime style we want to show (product management). it is light in color and (in the future) gives the user a possibility to add his own data with intense color, without making the map too heavy.

**Comment by boecklic** [comment]
@boecklic commented: Great job. Basis for sure. And + 1 to add them all.

**Comment by boecklic** [comment]
@boecklic commented: ok votes are done
proposal for loic just split the "switch layer" button to 3 buttons / radio buttons. lets name the style "A" "B" "C" not base lsd or grey

**Comment by boecklic** [comment]
@boecklic commented: @davidoesch  translations added in excelsheeet:


vector_feedback_style_default
vector_feedback_style_color
vector_feedback_style_grey
vector_feedback_style_lsd

**Comment by boecklic** [comment]
@boecklic commented: @davidoesch can you publish **lightbase**? **lightbase** (not **base**) is the style i have been working on and it is the one we want to show. the others are just quick derivations of it. from PM point of view **base** is actually the least important style and we might not want to publish it at all (it looks like our normal "Landeskarte" but just a lot worse). use **lightbase** as default. then i suggest we add **grey** and may be **LSD**? I'm open to other suggestions

**Comment by boecklic** [comment]
@boecklic commented: the style of **lightbase** with all tiles aggregated in one tileset: http://tileserver.int.bgdi.ch/styles/ch.swisstopo.leichte-basiskarte_aggregated_osm.vt_v004/?vector#12.89/47.56015/7.60972

**Comment by boecklic** [comment]
@boecklic commented: we  put buttons on one line

**Comment by boecklic** [comment]
@boecklic commented: translations done: set button on one line, thanks @loicgasser

**Comment by boecklic** [comment]
@boecklic commented: Ok will do

**Comment by boecklic** [comment]
@boecklic commented: thanks done

**Comment by boecklic** [comment]
@boecklic commented: Hi @loic the gls-sytles still point to my private repo: can you use this urls instead
- https://cms.geo.admin.ch/www.geo.admin.ch/cms_api/gl-styles/styles-ch.swisstopo.basiskarte-lsd.vt_v004.json

-https://cms.geo.admin.ch/www.geo.admin.ch/cms_api/gl-styles/styles-ch.swisstopo.basiskarte.vt_v004.json

- https://cms.geo.admin.ch/www.geo.admin.ch/cms_api/gl-styles/styles-ch.swisstopo.leichte-basiskarte.vt_v004.json

thanks

**Comment by boecklic** [comment]
@boecklic commented: We have other styles on public.geo.

Too many hosts, we have things everywhere.

Also, caching headers ok?

**Comment by boecklic** [comment]
@boecklic commented: You can put them on public.Geo ... No issue. It's importer that those styles are not pay of the official product...

**Comment by boecklic** [comment]
@boecklic commented: wait until we have v006

**Comment by boecklic** [comment]
@boecklic commented: in v006 all data will come from one mbtile:vektorkarte.vt (except the seperate osm data) and we will provide 3 styles: lightbase, grey and lsd (or just some really colorfull crazy stuff... not sure about it yet)

**Comment by boecklic** [comment]
@boecklic commented: hi @swissgis3084 
we have 
https://vectortiles.geo.admin.ch/gl-styles/ch.swisstopo.leichte-basiskarte-grey.vt/v006/?vector#7/47/8.25
https://vectortiles.geo.admin.ch/gl-styles/ch.swisstopo.leichte-basiskarte-vintage.vt/v006/?vector#7/47/8.25

but the colourful one we still use the same we have for v004?

**Comment by boecklic** [comment]
@boecklic commented: And here we go with the third variation

therefore we have now

A https://vectortiles.geo.admin.ch/gl-styles/ch.swisstopo.leichte-basiskarte-grey.vt/v006/?vector#7/47/8.25
B https://vectortiles.geo.admin.ch/gl-styles/ch.swisstopo.leichte-basiskarte-vintage.vt/v006/?vector#7/47/8.25
C http://tileserver.int.bgdi.ch/gl-styles/ch.swisstopo.leichte-basiskarte-lsd.vt/v006/?vector#7/47/8.5 

Store the style under cms.geo.admin.ch

**Comment by boecklic** [comment]
@boecklic commented: Hi @boecklic 

the stalye varation as above  can NOT be seved via the official vectortiles.geo.admin.ch  URL they need to have the warning

as mentioned above in the ticket-- you guys should not move it from my private repo to the official service but to CMS or a github repo

as a courtesy: I moved it already for you to cms.geo.admin.ch

A) https://cms.geo.admin.ch/www.geo.admin.ch/cms_api/gl-styles/ch.swisstopo.leichte-basiskarte-grey.vt_v006.json 
B) https://cms.geo.admin.ch/www.geo.admin.ch/cms_api/gl-styles/ch.swisstopo.leichte-basiskarte-vintage.vt_v006.json 
C) https://cms.geo.admin.ch/www.geo.admin.ch/cms_api/gl-styles/ch.swisstopo.leichte-basiskarte-lsd.vt_v006.json 

without this fiy we can't go live

**Comment by boecklic** [comment]
@boecklic commented: https://github.com/geoadmin/mf-geoadmin3/issues/4584#issuecomment-461021114 is not fixed 
is not attributed in [MVT] fixing background colour edition (GLStyle) #4820
![image](https://user-images.githubusercontent.com/4577727/56787789-e782b300-67fd-11e9-809c-9aaab40b5562.png)

**Comment by boecklic** [comment]
@boecklic commented: @pakb please check this too while solving the issue with the style edition...

**Comment by boecklic** [comment]
@boecklic commented: I don't understand what I'm supposed to do, styles are stored in cms.geo.admin.ch, changing background works too.
Please clarify

**Comment by boecklic** [comment]
@boecklic commented: in v006 all data will come from one mbtile:vektorkarte.vt (except the seperate osm data) and we will provide 3 styles: lightbase, grey and lsd (or just some really colorfull crazy stuff... not sure about it yet)

**Comment by boecklic** [comment]
@boecklic commented: Great job. Basis for sure. And + 1 to add them all.

**Comment by boecklic** [comment]
@boecklic commented: @pakb please check this too while solving the issue with the style edition...
