### ISSUE TITLE
[MVT] labels hide location circle on zoom 4

### ISSUE THREAD

**Issue by davidoesch** [geoadmin/mf-geoadmin3#4724]
open
https://test.map.geo.admin.ch/?lang=fr&topic=ech&bgLayer=ch.swisstopo.leichte-basiskarte.vt&layers_visibility=false&layers_timestamp=18641231&lon=7.70355&lat=46.55165&zoom=4

result
![image](https://user-images.githubusercontent.com/4577727/52178588-d0b95b00-27d0-11e9-8003-9e625fe16929.png)

expected result

labels don't cover circle

**Comment by pakb** [comment]
Will be addressed by https://github.com/geoadmin/mf-geoadmin3/issues/4732

**Comment by pakb** [comment]
Even with the font `Roboto` loaded, there are still some overlap, we're looking into this with https://github.com/openlayers/ol-mapbox-style/issues/170

**Comment by pakb** [comment]
fixed, see [the test viewer](https://test.map.geo.admin.ch)

**Comment by gjn** [comment]
this is still not fixed on all levels:
![image](https://user-images.githubusercontent.com/2572317/54106956-12dd4a00-43d8-11e9-9c49-c95609a277a7.png)


See
https://s.geo.admin.ch/8097048600

**Comment by boecklic** [comment]
Imho this can be closed
test.map.geo.admin:
![labels_above_circle_ol](https://user-images.githubusercontent.com/7808191/57062493-9ae91d00-6cc0-11e9-9510-ff20113a0cab.png)
the 'g' of Burgdorf is still overlapping the circle but it's exactly the same on pure mapbox:

Mapbox:
![labels_above_circle_mb](https://user-images.githubusercontent.com/7808191/57062498-9f153a80-6cc0-11e9-8359-6fb6ec1781dd.png)
